//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCD) DeepCopyInto(out *ArgoCD) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCD.
func (in *ArgoCD) DeepCopy() *ArgoCD {
	if in == nil {
		return nil
	}
	out := new(ArgoCD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDBS) DeepCopyInto(out *ArgoCDBS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDBS.
func (in *ArgoCDBS) DeepCopy() *ArgoCDBS {
	if in == nil {
		return nil
	}
	out := new(ArgoCDBS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackstageSecret) DeepCopyInto(out *BackstageSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackstageSecret.
func (in *BackstageSecret) DeepCopy() *BackstageSecret {
	if in == nil {
		return nil
	}
	out := new(BackstageSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTokenUrl) DeepCopyInto(out *ClusterTokenUrl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTokenUrl.
func (in *ClusterTokenUrl) DeepCopy() *ClusterTokenUrl {
	if in == nil {
		return nil
	}
	out := new(ClusterTokenUrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubBS) DeepCopyInto(out *GithubBS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubBS.
func (in *GithubBS) DeepCopy() *GithubBS {
	if in == nil {
		return nil
	}
	out := new(GithubBS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryCpu) DeepCopyInto(out *MemoryCpu) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryCpu.
func (in *MemoryCpu) DeepCopy() *MemoryCpu {
	if in == nil {
		return nil
	}
	out := new(MemoryCpu)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationEmailBS) DeepCopyInto(out *NotificationEmailBS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationEmailBS.
func (in *NotificationEmailBS) DeepCopy() *NotificationEmailBS {
	if in == nil {
		return nil
	}
	out := new(NotificationEmailBS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Orchestrator) DeepCopyInto(out *Orchestrator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Orchestrator.
func (in *Orchestrator) DeepCopy() *Orchestrator {
	if in == nil {
		return nil
	}
	out := new(Orchestrator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Orchestrator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestratorList) DeepCopyInto(out *OrchestratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Orchestrator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestratorList.
func (in *OrchestratorList) DeepCopy() *OrchestratorList {
	if in == nil {
		return nil
	}
	out := new(OrchestratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrchestratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestratorPlatform) DeepCopyInto(out *OrchestratorPlatform) {
	*out = *in
	out.SonataFlowPlatform = in.SonataFlowPlatform
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestratorPlatform.
func (in *OrchestratorPlatform) DeepCopy() *OrchestratorPlatform {
	if in == nil {
		return nil
	}
	out := new(OrchestratorPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestratorSpec) DeepCopyInto(out *OrchestratorSpec) {
	*out = *in
	out.SonataFlowOperator = in.SonataFlowOperator
	out.ServerlessOperator = in.ServerlessOperator
	out.RhdhOperator = in.RhdhOperator
	in.RhdhPlugins.DeepCopyInto(&out.RhdhPlugins)
	out.PostgresDB = in.PostgresDB
	out.OrchestratorPlatform = in.OrchestratorPlatform
	out.Tekton = in.Tekton
	out.ArgoCd = in.ArgoCd
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestratorSpec.
func (in *OrchestratorSpec) DeepCopy() *OrchestratorSpec {
	if in == nil {
		return nil
	}
	out := new(OrchestratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestratorStatus) DeepCopyInto(out *OrchestratorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestratorStatus.
func (in *OrchestratorStatus) DeepCopy() *OrchestratorStatus {
	if in == nil {
		return nil
	}
	out := new(OrchestratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginDetails) DeepCopyInto(out *PluginDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginDetails.
func (in *PluginDetails) DeepCopy() *PluginDetails {
	if in == nil {
		return nil
	}
	out := new(PluginDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Postgres) DeepCopyInto(out *Postgres) {
	*out = *in
	out.AuthSecret = in.AuthSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Postgres.
func (in *Postgres) DeepCopy() *Postgres {
	if in == nil {
		return nil
	}
	out := new(Postgres)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresAuthSecret) DeepCopyInto(out *PostgresAuthSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresAuthSecret.
func (in *PostgresAuthSecret) DeepCopy() *PostgresAuthSecret {
	if in == nil {
		return nil
	}
	out := new(PostgresAuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHDHOperator) DeepCopyInto(out *RHDHOperator) {
	*out = *in
	out.Subscription = in.Subscription
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHDHOperator.
func (in *RHDHOperator) DeepCopy() *RHDHOperator {
	if in == nil {
		return nil
	}
	out := new(RHDHOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHDHPlugins) DeepCopyInto(out *RHDHPlugins) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make(map[string]PluginDetails, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.NotificationConfig = in.NotificationConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHDHPlugins.
func (in *RHDHPlugins) DeepCopy() *RHDHPlugins {
	if in == nil {
		return nil
	}
	out := new(RHDHPlugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRefBS) DeepCopyInto(out *SecretRefBS) {
	*out = *in
	out.Backstage = in.Backstage
	out.Github = in.Github
	out.ClusterTokenUrl = in.ClusterTokenUrl
	out.ArgoCD = in.ArgoCD
	out.NotificationEmail = in.NotificationEmail
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRefBS.
func (in *SecretRefBS) DeepCopy() *SecretRefBS {
	if in == nil {
		return nil
	}
	out := new(SecretRefBS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerlessOperator) DeepCopyInto(out *ServerlessOperator) {
	*out = *in
	out.Subscription = in.Subscription
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerlessOperator.
func (in *ServerlessOperator) DeepCopy() *ServerlessOperator {
	if in == nil {
		return nil
	}
	out := new(ServerlessOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowOperator) DeepCopyInto(out *SonataFlowOperator) {
	*out = *in
	out.Subscription = in.Subscription
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowOperator.
func (in *SonataFlowOperator) DeepCopy() *SonataFlowOperator {
	if in == nil {
		return nil
	}
	out := new(SonataFlowOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowPlatform) DeepCopyInto(out *SonataFlowPlatform) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowPlatform.
func (in *SonataFlowPlatform) DeepCopy() *SonataFlowPlatform {
	if in == nil {
		return nil
	}
	out := new(SonataFlowPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subscription) DeepCopyInto(out *Subscription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subscription.
func (in *Subscription) DeepCopy() *Subscription {
	if in == nil {
		return nil
	}
	out := new(Subscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tekton) DeepCopyInto(out *Tekton) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tekton.
func (in *Tekton) DeepCopy() *Tekton {
	if in == nil {
		return nil
	}
	out := new(Tekton)
	in.DeepCopyInto(out)
	return out
}
