apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
  description: Team A
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest.user@example.com
  memberOf: [development]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev1
spec:
  profile:
    displayName: Developer 1
  memberOf: [development]